# Generated by Django 5.2.5 on 2025-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reservation_time', models.DateTimeField(auto_now=True)),
                ('guest_count', models.PositiveIntegerField()),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
    ]
